name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libglib2.0-dev \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            pkg-config \
            build-essential

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Install client dependencies (include dev)
        run: npm ci --include=dev
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install backend test dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r backend/requirements-build.txt fastapi pytest httpx

      - name: Run backend tests
        run: pytest -q backend
        working-directory: client

      - name: Build React client
        run: npm run build
        working-directory: client

      - name: Run client unit tests
        run: npm run -s test
        working-directory: client

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cargo fmt
        run: cargo fmt --all -- --check
        working-directory: client/src-tauri

      - name: Cargo test
        run: cargo test --all --release
        working-directory: client/src-tauri

      - name: Cargo clippy
        run: cargo clippy --all-targets -- -D warnings
        working-directory: client/src-tauri
